#ifndef DECODE_CFG_H_
#define DECODE_CFG_H_
//////////////////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
extern "C" {
	#endif
	//////////////////////////////////////////////////////////////////////////////////////
	#include "complier_lib.h"
	#include "gpio_task.h"
	#include "timer_task.h"
	#include "delay_task.h"
	#include "rfaskhw_cfg.h"
	#include "rfask_task.h"
	#include "systick_task.h"
	//////////////////////////////////////////////////////////////////////////////////////
	//===解码使用的定时器
	#define DECODE_USE_TIM								TIM2
	//===解码定时器中断
	#define DECODE_USE_TIM_IRQ							TIM2_IRQn

	//===A通道解码
	#define DECA_CH_PORT								GPIOA
	#define DECA_CH_BIT									LL_GPIO_PIN_0
	#define DECA_CH_STATE								GPIO_GET_STATE(DECA_CH_PORT,DECA_CH_BIT)
	#define DECA_CH_WRITE								GPIO_SET_WRITE(DECA_CH_PORT,DECA_CH_BIT)
	#define DECA_CH_READ								GPIO_SET_READ( DECA_CH_PORT,DECA_CH_BIT)
	#define DECA_CH_OUT_0								GPIO_OUT_0(    DECA_CH_PORT,DECA_CH_BIT)
	#define DECA_CH_OUT_1								GPIO_OUT_1(    DECA_CH_PORT,DECA_CH_BIT)
	#define DECA_CH_OUT_C								GPIO_OUT_C(    DECA_CH_PORT,DECA_CH_BIT)

	//===B通道解码
	#define DECB_CH_PORT								GPIOA
	#define DECB_CH_BIT									LL_GPIO_PIN_1
	#define DECB_CH_STATE								GPIO_GET_STATE(DECB_CH_PORT,DECB_CH_BIT)
	#define DECB_CH_WRITE								GPIO_SET_WRITE(DECB_CH_PORT,DECB_CH_BIT)
	#define DECB_CH_READ								GPIO_SET_READ( DECB_CH_PORT,DECB_CH_BIT)
	#define DECB_CH_OUT_0								GPIO_OUT_0(    DECB_CH_PORT,DECB_CH_BIT)
	#define DECB_CH_OUT_1								GPIO_OUT_1(    DECB_CH_PORT,DECB_CH_BIT)
	#define DECB_CH_OUT_C								GPIO_OUT_C(    DECB_CH_PORT,DECB_CH_BIT)

	//===C通道解码
	#define DECC_CH_PORT								GPIOA
	#define DECC_CH_BIT									LL_GPIO_PIN_2
	#define DECC_CH_STATE								GPIO_GET_STATE(DECC_CH_PORT,DECC_CH_BIT)
	#define DECC_CH_WRITE								GPIO_SET_WRITE(DECC_CH_PORT,DECC_CH_BIT)
	#define DECC_CH_READ								GPIO_SET_READ( DECC_CH_PORT,DECC_CH_BIT)
	#define DECC_CH_OUT_0								GPIO_OUT_0(    DECC_CH_PORT,DECC_CH_BIT)
	#define DECC_CH_OUT_1								GPIO_OUT_1(    DECC_CH_PORT,DECC_CH_BIT)
	#define DECC_CH_OUT_C								GPIO_OUT_C(    DECC_CH_PORT,DECC_CH_BIT)

	//===D通道解码
	#define DECD_CH_PORT								GPIOA
	#define DECD_CH_BIT									LL_GPIO_PIN_3
	#define DECD_CH_STATE								GPIO_GET_STATE(DECD_CH_PORT,DECD_CH_BIT)
	#define DECD_CH_WRITE								GPIO_SET_WRITE(DECD_CH_PORT,DECD_CH_BIT)
	#define DECD_CH_READ								GPIO_SET_READ( DECD_CH_PORT,DECD_CH_BIT)
	#define DECD_CH_OUT_0								GPIO_OUT_0(    DECD_CH_PORT,DECD_CH_BIT)
	#define DECD_CH_OUT_1								GPIO_OUT_1(    DECD_CH_PORT,DECD_CH_BIT)
	#define DECD_CH_OUT_C								GPIO_OUT_C(    DECD_CH_PORT,DECD_CH_BIT)

	//===A通道解码实时灯
	#define DECA_LED_PORT								GPIOB
	#define DECA_LED_BIT								LL_GPIO_PIN_11
	#define DECA_LED_STATE								GPIO_GET_STATE(DECA_LED_PORT,DECA_LED_BIT)
	#define DECA_LED_WRITE								GPIO_SET_WRITE(DECA_LED_PORT,DECA_LED_BIT)
	#define DECA_LED_READ								GPIO_SET_READ( DECA_LED_PORT,DECA_LED_BIT)
	#define DECA_LED_OUT_0								GPIO_OUT_0(    DECA_LED_PORT,DECA_LED_BIT)
	#define DECA_LED_OUT_1								GPIO_OUT_1(    DECA_LED_PORT,DECA_LED_BIT)
	#define DECA_LED_OUT_C								GPIO_OUT_C(    DECA_LED_PORT,DECA_LED_BIT)
	#define DECA_LED_IS_ON								DECA_LED_OUT_1
	#define DECA_LED_IS_OFF								DECA_LED_OUT_0

	//===B通道解码实时灯
	#define DECB_LED_PORT								GPIOB
	#define DECB_LED_BIT								LL_GPIO_PIN_12
	#define DECB_LED_STATE								GPIO_GET_STATE(DECB_LED_PORT,DECB_LED_BIT)
	#define DECB_LED_WRITE								GPIO_SET_WRITE(DECB_LED_PORT,DECB_LED_BIT)
	#define DECB_LED_READ								GPIO_SET_READ( DECB_LED_PORT,DECB_LED_BIT)
	#define DECB_LED_OUT_0								GPIO_OUT_0(    DECB_LED_PORT,DECB_LED_BIT)
	#define DECB_LED_OUT_1								GPIO_OUT_1(    DECB_LED_PORT,DECB_LED_BIT)
	#define DECB_LED_OUT_C								GPIO_OUT_C(    DECB_LED_PORT,DECB_LED_BIT)
	#define DECB_LED_IS_ON								DECB_LED_OUT_1
	#define DECB_LED_IS_OFF								DECB_LED_OUT_0

	//===C通道解码实时灯
	#define DECC_LED_PORT								GPIOB
	#define DECC_LED_BIT								LL_GPIO_PIN_13
	#define DECC_LED_STATE								GPIO_GET_STATE(DECC_LED_PORT,DECC_LED_BIT)
	#define DECC_LED_WRITE								GPIO_SET_WRITE(DECC_LED_PORT,DECC_LED_BIT)
	#define DECC_LED_READ								GPIO_SET_READ( DECC_LED_PORT,DECC_LED_BIT)
	#define DECC_LED_OUT_0								GPIO_OUT_0(    DECC_LED_PORT,DECC_LED_BIT)
	#define DECC_LED_OUT_1								GPIO_OUT_1(    DECC_LED_PORT,DECC_LED_BIT)
	#define DECC_LED_OUT_C								GPIO_OUT_C(    DECC_LED_PORT,DECC_LED_BIT)
	#define DECC_LED_IS_ON								DECC_LED_OUT_1
	#define DECC_LED_IS_OFF								DECC_LED_OUT_0

	//===D通道解码实时灯
	#define DECD_LED_PORT								GPIOB
	#define DECD_LED_BIT								LL_GPIO_PIN_14
	#define DECD_LED_STATE								GPIO_GET_STATE(DECD_LED_PORT,DECD_LED_BIT)
	#define DECD_LED_WRITE								GPIO_SET_WRITE(DECD_LED_PORT,DECD_LED_BIT)
	#define DECD_LED_READ								GPIO_SET_READ( DECD_LED_PORT,DECD_LED_BIT)
	#define DECD_LED_OUT_0								GPIO_OUT_0(    DECD_LED_PORT,DECD_LED_BIT)
	#define DECD_LED_OUT_1								GPIO_OUT_1(    DECD_LED_PORT,DECD_LED_BIT)
	#define DECD_LED_OUT_C								GPIO_OUT_C(    DECD_LED_PORT,DECD_LED_BIT)
	#define DECD_LED_IS_ON								DECD_LED_OUT_1
	#define DECD_LED_IS_OFF								DECD_LED_OUT_0

	//===关闭实时解码灯
	#define DEC_LED_OFF									( DECA_LED_OUT_0,DECB_LED_OUT_0,DECC_LED_OUT_0,DECD_LED_OUT_0 )

	//===A通道解码RST复位标志
	#define DECA_RST_PORT								RSTA_PORT//GPIOE
	#define DECA_RST_BIT								RSTA_BIT //LL_GPIO_PIN_14
	#define DECA_RST_STATE								GPIO_GET_STATE(DECA_RST_PORT,DECA_RST_BIT)
	#define DECA_RST_WRITE								GPIO_SET_WRITE(DECA_RST_PORT,DECA_RST_BIT)
	#define DECA_RST_READ								GPIO_SET_READ( DECA_RST_PORT,DECA_RST_BIT)
	#define DECA_RST_OUT_0								GPIO_OUT_0(    DECA_RST_PORT,DECA_RST_BIT)
	#define DECA_RST_OUT_1								GPIO_OUT_1(    DECA_RST_PORT,DECA_RST_BIT)
	#define DECA_RST_OUT_C								GPIO_OUT_C(    DECA_RST_PORT,DECA_RST_BIT)

	//===B通道解码RST复位标志
	#define DECB_RST_PORT								RSTB_PORT//GPIOE
	#define DECB_RST_BIT								RSTB_BIT//LL_GPIO_PIN_5
	#define DECB_RST_STATE								GPIO_GET_STATE(DECB_RST_PORT,DECB_RST_BIT)
	#define DECB_RST_WRITE								GPIO_SET_WRITE(DECB_RST_PORT,DECB_RST_BIT)
	#define DECB_RST_READ								GPIO_SET_READ( DECB_RST_PORT,DECB_RST_BIT)
	#define DECB_RST_OUT_0								GPIO_OUT_0(    DECB_RST_PORT,DECB_RST_BIT)
	#define DECB_RST_OUT_1								GPIO_OUT_1(    DECB_RST_PORT,DECB_RST_BIT)
	#define DECB_RST_OUT_C								GPIO_OUT_C(    DECB_RST_PORT,DECB_RST_BIT)

	//===C通道解码RST复位标志
	#define DECC_RST_PORT								RSTC_PORT//GPIOD
	#define DECC_RST_BIT								RSTC_BIT //LL_GPIO_PIN_0
	#define DECC_RST_STATE								GPIO_GET_STATE(DECC_RST_PORT,DECC_RST_BIT)
	#define DECC_RST_WRITE								GPIO_SET_WRITE(DECC_RST_PORT,DECC_RST_BIT)
	#define DECC_RST_READ								GPIO_SET_READ( DECC_RST_PORT,DECC_RST_BIT)
	#define DECC_RST_OUT_0								GPIO_OUT_0(    DECC_RST_PORT,DECC_RST_BIT)
	#define DECC_RST_OUT_1								GPIO_OUT_1(    DECC_RST_PORT,DECC_RST_BIT)
	#define DECC_RST_OUT_C								GPIO_OUT_C(    DECC_RST_PORT,DECC_RST_BIT)

	//===D通道解码RST复位标志
	#define DECD_RST_PORT								RSTD_PORT//GPIOD
	#define DECD_RST_BIT								RSTD_BIT //LL_GPIO_PIN_8
	#define DECD_RST_STATE								GPIO_GET_STATE(DECD_RST_PORT,DECD_RST_BIT)
	#define DECD_RST_WRITE								GPIO_SET_WRITE(DECD_RST_PORT,DECD_RST_BIT)
	#define DECD_RST_READ								GPIO_SET_READ( DECD_RST_PORT,DECD_RST_BIT)
	#define DECD_RST_OUT_0								GPIO_OUT_0(    DECD_RST_PORT,DECD_RST_BIT)
	#define DECD_RST_OUT_1								GPIO_OUT_1(    DECD_RST_PORT,DECD_RST_BIT)
	#define DECD_RST_OUT_C								GPIO_OUT_C(    DECD_RST_PORT,DECD_RST_BIT)

	//===A通道解码通过的配置
	#define DECA_PASS_CTR_PORT							DECA_PASS_PORT//GPIOE
	#define DECA_PASS_CTR_BIT							DECA_PASS_BIT //LL_GPIO_PIN_15
	#define DECA_PASS_CTR_STATE							GPIO_GET_STATE(DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_WRITE							GPIO_SET_WRITE(DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_READ							GPIO_SET_READ( DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_OUT_0							GPIO_OUT_0(    DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_OUT_1							GPIO_OUT_1(    DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_CTR_OUT_C							GPIO_OUT_C(    DECA_PASS_CTR_PORT,DECA_PASS_CTR_BIT)
	#define DECA_PASS_OK								DECA_PASS_CTR_OUT_0
	#define DECA_PASS_FAIL								DECA_PASS_CTR_OUT_1

	//===B通道解码通过的配置
	#define DECB_PASS_CTR_PORT							DECB_PASS_PORT//GPIOE
	#define DECB_PASS_CTR_BIT							DECB_PASS_BIT //LL_GPIO_PIN_6
	#define DECB_PASS_CTR_STATE							GPIO_GET_STATE(DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_WRITE							GPIO_SET_WRITE(DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_READ							GPIO_SET_READ( DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_OUT_0							GPIO_OUT_0(    DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_OUT_1							GPIO_OUT_1(    DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_CTR_OUT_C							GPIO_OUT_C(    DECB_PASS_CTR_PORT,DECB_PASS_CTR_BIT)
	#define DECB_PASS_OK								DECB_PASS_CTR_OUT_0
	#define DECB_PASS_FAIL								DECB_PASS_CTR_OUT_1

	//===C通道解码通过的配置
	#define DECC_PASS_CTR_PORT							DECC_PASS_PORT//GPIOC
	#define DECC_PASS_CTR_BIT							DECC_PASS_BIT //LL_GPIO_PIN_12
	#define DECC_PASS_CTR_STATE							GPIO_GET_STATE(DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_WRITE							GPIO_SET_WRITE(DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_READ							GPIO_SET_READ( DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_OUT_0							GPIO_OUT_0(    DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_OUT_1							GPIO_OUT_1(    DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_CTR_OUT_C							GPIO_OUT_C(    DECC_PASS_CTR_PORT,DECC_PASS_CTR_BIT)
	#define DECC_PASS_OK								DECC_PASS_CTR_OUT_0
	#define DECC_PASS_FAIL								DECC_PASS_CTR_OUT_1

	//===D通道解码通过的配置
	#define DECD_PASS_CTR_PORT							DECD_PASS_PORT//GPIOB
	#define DECD_PASS_CTR_BIT							DECD_PASS_BIT //LL_GPIO_PIN_15
	#define DECD_PASS_CTR_STATE							GPIO_GET_STATE(DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_WRITE							GPIO_SET_WRITE(DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_READ							GPIO_SET_READ( DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_OUT_0							GPIO_OUT_0(    DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_OUT_1							GPIO_OUT_1(    DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_CTR_OUT_C							GPIO_OUT_C(    DECD_PASS_CTR_PORT,DECD_PASS_CTR_BIT)
	#define DECD_PASS_OK								DECD_PASS_CTR_OUT_0
	#define DECD_PASS_FAIL								DECD_PASS_CTR_OUT_1

	#define DEC_PASS_OK									( DECA_PASS_OK,DECB_PASS_OK,DECC_PASS_OK,DECD_PASS_OK )
	#define DEC_PASS_FAIL								( DECA_PASS_FAIL,DECB_PASS_FAIL,DECC_PASS_FAIL,DECD_PASS_FAIL )

	#define DECA_WAVE_CTR_PORT							DECA_WAVE_PORT//GPIOB
	#define DECA_WAVE_CTR_BIT							DECA_WAVE_BIT //LL_GPIO_PIN_15
	#define DECA_WAVE_CTR_STATE							GPIO_GET_STATE(DECA_WAVE_CTR_PORT,DECA_WAVE_CTR_BIT)
	#define DECA_WAVE_CTR_WRITE							GPIO_SET_WRITE(DECA_WAVE_CTR_PORT,DECA_WAVE_CTR_BIT)
	#define DECA_WAVE_CTR_READ							GPIO_SET_READ( DECA_WAVE_CTR_PORT,DECA_WAVE_CTR_BIT)
	#define DECA_WAVE_CTR_OUT_0							GPIO_OUT_0(    DECA_WAVE_CTR_PORT,DECA_WAVE_CTR_BIT)
	#define DECA_WAVE_CTR_OUT_1							GPIO_OUT_1(    DECA_WAVE_CTR_PORT,DECA_WAVE_CTR_BIT)
	#define DECA_WAVE_CTR_OUT_C							GPIO_OUT_C(    DECA_WAVE_CTR_PORT,DECA_WAVE_CTR_BIT)

	#define DECB_WAVE_CTR_PORT							DECB_WAVE_PORT//GPIOB
	#define DECB_WAVE_CTR_BIT							DECB_WAVE_BIT //LL_GPIO_PIN_15
	#define DECB_WAVE_CTR_STATE							GPIO_GET_STATE(DECB_WAVE_CTR_PORT,DECB_WAVE_CTR_BIT)
	#define DECB_WAVE_CTR_WRITE							GPIO_SET_WRITE(DECB_WAVE_CTR_PORT,DECB_WAVE_CTR_BIT)
	#define DECB_WAVE_CTR_READ							GPIO_SET_READ( DECB_WAVE_CTR_PORT,DECB_WAVE_CTR_BIT)
	#define DECB_WAVE_CTR_OUT_0							GPIO_OUT_0(    DECB_WAVE_CTR_PORT,DECB_WAVE_CTR_BIT)
	#define DECB_WAVE_CTR_OUT_1							GPIO_OUT_1(    DECB_WAVE_CTR_PORT,DECB_WAVE_CTR_BIT)
	#define DECB_WAVE_CTR_OUT_C							GPIO_OUT_C(    DECB_WAVE_CTR_PORT,DECB_WAVE_CTR_BIT)
	
	#define DECC_WAVE_CTR_PORT							DECC_WAVE_PORT//GPIOB
	#define DECC_WAVE_CTR_BIT							DECC_WAVE_BIT //LL_GPIO_PIN_15
	#define DECC_WAVE_CTR_STATE							GPIO_GET_STATE(DECC_WAVE_CTR_PORT,DECC_WAVE_CTR_BIT)
	#define DECC_WAVE_CTR_WRITE							GPIO_SET_WRITE(DECC_WAVE_CTR_PORT,DECC_WAVE_CTR_BIT)
	#define DECC_WAVE_CTR_READ							GPIO_SET_READ( DECC_WAVE_CTR_PORT,DECC_WAVE_CTR_BIT)
	#define DECC_WAVE_CTR_OUT_0							GPIO_OUT_0(    DECC_WAVE_CTR_PORT,DECC_WAVE_CTR_BIT)
	#define DECC_WAVE_CTR_OUT_1							GPIO_OUT_1(    DECC_WAVE_CTR_PORT,DECC_WAVE_CTR_BIT)
	#define DECC_WAVE_CTR_OUT_C							GPIO_OUT_C(    DECC_WAVE_CTR_PORT,DECC_WAVE_CTR_BIT)
	
	#define DECD_WAVE_CTR_PORT							DECD_WAVE_PORT//GPIOB
	#define DECD_WAVE_CTR_BIT							DECD_WAVE_BIT //LL_GPIO_PIN_15
	#define DECD_WAVE_CTR_STATE							GPIO_GET_STATE(DECD_WAVE_CTR_PORT,DECD_WAVE_CTR_BIT)
	#define DECD_WAVE_CTR_WRITE							GPIO_SET_WRITE(DECD_WAVE_CTR_PORT,DECD_WAVE_CTR_BIT)
	#define DECD_WAVE_CTR_READ							GPIO_SET_READ( DECD_WAVE_CTR_PORT,DECD_WAVE_CTR_BIT)
	#define DECD_WAVE_CTR_OUT_0							GPIO_OUT_0(    DECD_WAVE_CTR_PORT,DECD_WAVE_CTR_BIT)
	#define DECD_WAVE_CTR_OUT_1							GPIO_OUT_1(    DECD_WAVE_CTR_PORT,DECD_WAVE_CTR_BIT)
	#define DECD_WAVE_CTR_OUT_C							GPIO_OUT_C(    DECD_WAVE_CTR_PORT,DECD_WAVE_CTR_BIT)
		
	//===解码波形是连续方波
	#define DECODE_WAVE_SQUARE							0
	//===解码波形是帧停顿方波
	#define DECODE_WAVE_FREME_SQUARE					1
	//===解码波形是PT2262	
	#define DECODE_WAVE_PT2262							2
	//===解码电平的上升沿
	#define DECODE_LEVEL_NONE							0
	//===解码电平的上升沿
	#define DECODE_LEVEL_HIGH							1
	//===解码电平的下降沿
	#define DECODE_LEVEL_LOW							2
	//===解码电平的上升沿
	#define DECODE_LEVEL_MASK							3
	//===解码SITE数
	#define DECODE_SITE_COUNT							4
	//===检查SITE数
	#if( DECODE_SITE_COUNT==0)
		#undef	DECODE_SITE_COUNT
		#define	DECODE_SITE_COUNT						1
		#warning "DECODE_SITE_COUNT不能小于24"
	#elif (DECODE_SITE_COUNT>4)
		#undef	DECODE_SITE_COUNT
		#define	DECODE_SITE_COUNT						4
		#warning "DECODE_SITE_COUNT不能大大于4"
	#endif

	//===定时器解码的定时时间的采样率
	#define DECODE_TIME_SAMPLE_RATE_KHZ					1000	
	//===定时器重新装载值
	#define	DECODE_TIM_RELOAD							(UINT32_T)50000
	//===解码采样时钟为72MHz, 采样周期1us; 计数器的最大值为50000，时间1us，最大记录同电平保持时间为50ms
	#define DECODE_TIM_ARR								( ((SYS_CLOCK_MHZ*1000)/DECODE_TIME_SAMPLE_RATE_KHZ)-1)

	//===占空比解码的脉宽占空比1:1=50;1:3==25;3:7=30
	#define DECODE_SQUARE_WIDTH_RATE					40
	//===PT2262的脉宽占空比1:1=50;1:3==25;3:7=30
	#define DECODE_PT2262_WIDTH_RATE					30
	//===加帧方波的脉宽占空比1:1=50;1:3==25;3:7=30
	#define DECODE_FRAME_WIDTH_RATE						40
	//===脉冲宽度的容差值
	#define DECODE_WIDTH_ABS_ERROR						0
	//===解码的最小脉冲宽度,单位是us
	#define DECODE_PULSE_BASE_WIDTH						( DECODE_TIME_SAMPLE_RATE_KHZ/2 )

	//===连续方波脉宽最小值
	#define DECODE_SQUARE_WIDTH_MAX						( ( ( DECODE_PULSE_BASE_WIDTH*2*( 100-DECODE_SQUARE_WIDTH_RATE ) )/100)+DECODE_WIDTH_ABS_ERROR )
	//===连续方波脉宽最大值
	#define DECODE_SQUARE_WIDTH_MIN						( ( ( DECODE_PULSE_BASE_WIDTH*2*( DECODE_SQUARE_WIDTH_RATE ) )/100)-DECODE_WIDTH_ABS_ERROR )

	//===连续方波脉宽最小值
	#define DECODE_FRAME_WIDTH_MAX						( ( ( DECODE_PULSE_BASE_WIDTH*2*( 100-DECODE_FRAME_WIDTH_RATE ) )/100)+DECODE_WIDTH_ABS_ERROR )
	//===连续方波脉宽最大值
	#define DECODE_FRAME_WIDTH_MIN						( ( ( DECODE_PULSE_BASE_WIDTH*2*( DECODE_FRAME_WIDTH_RATE ) )/100)-DECODE_WIDTH_ABS_ERROR )

	//===加帧方波脉宽最小值
	#define DECODE_FRAME_START_WIDTH_MAX				( ( ( DECODE_PULSE_BASE_WIDTH*2*( 100-30 ) )/100)+DECODE_WIDTH_ABS_ERROR )
	//===加帧方波脉宽最大值
	#define DECODE_FRAME_START_WIDTH_MIN				( ( ( DECODE_PULSE_BASE_WIDTH*2*( 30 ) )/100)-DECODE_WIDTH_ABS_ERROR )

	//===PT2262的帧停顿的最大值
	#define DECODE_FRAME_PAUSE_MAX						(  DECODE_PULSE_BASE_WIDTH*2*(15+2)+DECODE_PULSE_BASE_WIDTH )
	//===PT2262的帧停顿的最小值
	#define DECODE_FRAME_PAUSE_MIN						(  DECODE_PULSE_BASE_WIDTH*2*(15-2)-DECODE_PULSE_BASE_WIDTH )

	//===PT2262的窄脉冲最大值
	#define DECODE_PT2262_NARROW_WIDTH_MAX				( ( ( DECODE_PULSE_BASE_WIDTH*2*( 100-DECODE_PT2262_WIDTH_RATE ) )/100)+DECODE_WIDTH_ABS_ERROR )
	//===PT2262的窄脉冲最小值
	#define DECODE_PT2262_NARROW_WIDTH_MIN				( ( ( DECODE_PULSE_BASE_WIDTH*2*( DECODE_PT2262_WIDTH_RATE ) )/100)-DECODE_WIDTH_ABS_ERROR )

	//===PT2262的宽脉冲最大值
	#define DECODE_PT2262_WIDE_WIDTH_MAX				(  DECODE_PULSE_BASE_WIDTH*4-DECODE_PT2262_NARROW_WIDTH_MIN )
	//===PT2262的宽脉冲最小值
	#define DECODE_PT2262_WIDE_WIDTH_MIN				(  DECODE_PULSE_BASE_WIDTH*4-DECODE_PT2262_NARROW_WIDTH_MAX )

	//===PT2262的帧停顿的最大值
	#define DECODE_PT2262_FRAME_PAUSE_MAX				(  DECODE_PULSE_BASE_WIDTH*2*(15+2)+DECODE_PULSE_BASE_WIDTH )
	//===PT2262的帧停顿的最小值
	#define DECODE_PT2262_FRAME_PAUSE_MIN				(  DECODE_PULSE_BASE_WIDTH*2*(15-2)-DECODE_PULSE_BASE_WIDTH )
	

	//===解码合格的计数，连续方波
	#define	DECODE_SQUARE_PASS_MAX_COUNT				80
	//===加帧方波解码合格计数
	#define DECODE_FREAME_PASS_MAX_COUNT				47
	//===加帧方波解码合格限定次数，大于等于此值，才算解码通过
	#define DECODE_FRAME_PASS_FRAME_MIN_COUNT			2
	//===加帧方波连续帧解码合格限定次数，大于等于此值，才算解码通过
	#define DECODE_FREAME_PASS_FRAME_MIN_COUNT			2
	//===PT2262解码通过的值
	#define DECODE_PT2262_PASS_MAX_COUNT				24
	//===PT2262连续帧解码合格限定次数，大于等于此值，才算解码通过
	#define DECODE_PT2262_PASS_FRAME_MIN_COUNT			2


	//===相同电平保持的最长时间，时间单位是ms
	#define DECODE_SAME_LEVEL_MAX_WIDTH					30
	//===帧停顿之后的开始多少个脉冲计算开始计数
	#define DECODE_FRAME_PAUSE_COUNT_INDEX				4
	
	//===检查数据的合理性
	#if(DECODE_BIT_COUNT > 24)
		#undef	DECODE_BIT_COUNT
		#define	DECODE_BIT_COUNT						24
		#warning "DECODE_BIT_COUNT不能大于24"
	#endif

	//===解码步序
	#define DECODE_STEP_0								0
	#define DECODE_STEP_1								(DECODE_STEP_0 + 1)
	#define DECODE_STEP_2								(DECODE_STEP_1 + 1)
	#define DECODE_STEP_3								(DECODE_STEP_2 + 1)
	#define DECODE_STEP_4								(DECODE_STEP_3 + 1)
	#define DECODE_STEP_5								(DECODE_STEP_4 + 1)
	#define DECODE_STEP_6								(DECODE_STEP_5 + 1)
	#define DECODE_STEP_7								(DECODE_STEP_6 + 1)
	#define DECODE_STEP_8								(DECODE_STEP_7 + 1)
	#define DECODE_STEP_9								(DECODE_STEP_8 + 1)
	#define DECODE_STEP_10								(DECODE_STEP_9 + 1)
	#define DECODE_STEP_11								(DECODE_STEP_10 + 1)
	#define DECODE_STEP_12								(DECODE_STEP_11 + 1)
	#define DECODE_STEP_13								(DECODE_STEP_12 + 1)
	#define DECODE_STEP_14								(DECODE_STEP_13 + 1)
	#define DECODE_STEP_15								(DECODE_STEP_14 + 1)
	#define DECODE_STEP_16								(DECODE_STEP_15 + 1)

	//===函数定义
	void	Decode_Init(void);
	void	Decode_START(void);
	void	Decode_STOP(void);
	void	Decode_ActivateSites(UINT8_T activateSites);
	void	Decode_ClearActivateSites(void);
	void	Decode_ClearState(void);
	UINT8_T Decode_ScanRST(void);
	void	Decode_IRQTask(void);
	void	Decode_Query(void);
	//////////////////////////////////////////////////////////////////////////////////////
	#ifdef __cplusplus
}
#endif
//////////////////////////////////////////////////////////////////////////////////////
#endif /*DECODE_CFG_H_ */